"""
Unit tests for GD Evaluation MongoDB Repository (backend/services/gd_repository.py).

All tests use a mocked PyMongo collection to run deterministically and offline.
"""

from datetime import datetime, timezone
from unittest.mock import MagicMock, patch
import pytest
from pymongo.errors import PyMongoError

import backend.services.gd_repository as gd_repo


@pytest.fixture
def sample_gd_result():
    """Returns a full structured result as generated by GDEvaluationService.evaluate_session()."""
    return {
        "session_id": "GD-SESSION-101",
        "topic": "Impact of Artificial Intelligence on Higher Education",
        "session_duration": 185.42,
        "group_transcript": "[0.0s - 12.5s] P1: AI enhances learning.\n[13.0s - 25.0s] P2: But critical thinking is key.",
        "group_segments": [
            {
                "participant_id": "P1",
                "start": 0.0,
                "end": 12.5,
                "text": "AI enhances learning.",
                "duration": 12.5,
            },
            {
                "participant_id": "P2",
                "start": 13.0,
                "end": 25.0,
                "text": "But critical thinking is key.",
                "duration": 12.0,
            },
        ],
        "participants": [
            {
                "participant_id": "P1",
                "audio_path": "uploads/gd_sessions/p1.wav",
                "session_offset": 0.0,
                "transcript": "AI enhances learning.",
                "transcript_segments": [{"start": 0.0, "end": 12.5, "text": "AI enhances learning."}],
                "vad_segments": [{"start": 0.0, "end": 12.5}],
                "speaking_time": 12.5,
                "word_count": 3,
                "turn_count": 1,
                "features": {
                    "speaking_duration": 12.5,
                    "speaking_percentage": 50.0,
                    "wpm": 14.4,
                    "turn_count": 1,
                    "avg_turn_duration": 12.5,
                    "silence_duration": 0.0,
                },
                "interaction_features": {
                    "response_latency_avg": 0.0,
                    "interruptions_made": 0,
                    "interruptions_received": 0,
                    "overlaps_count": 0,
                },
                "agent_results": [
                    {"agent_name": "relevance", "score": 8.5, "feedback": "Relevant"},
                ],
                "scorecard": {
                    "relevance": 8.5,
                    "coherence": 8.0,
                    "fluency": 7.5,
                    "participation": 7.0,
                    "final_score": 7.75,
                },
                "final_score": 7.75,
            },
        ],
        "participant_transcripts": {
            "P1": "AI enhances learning.",
            "P2": "But critical thinking is key.",
        },
        "objective_features": {
            "P1": {"speaking_duration": 12.5, "wpm": 14.4},
            "P2": {"speaking_duration": 12.0, "wpm": 15.0},
        },
        "interaction_features": {
            "P1": {"response_latency_avg": 0.0},
            "P2": {"response_latency_avg": 0.5},
        },
        "agent_results": {
            "P1": [{"agent_name": "relevance", "score": 8.5}],
            "P2": [{"agent_name": "relevance", "score": 8.0}],
        },
        "scorecards": {
            "P1": {"final_score": 7.75},
            "P2": {"final_score": 8.00},
        },
        "final_scores": {
            "P1": 7.75,
            "P2": 8.00,
        },
    }


# ==============================================================================
# SAVE EVALUATION TESTS
# ==============================================================================

def test_save_evaluation_success(sample_gd_result):
    """Test saving a complete GD evaluation structure."""
    mock_collection = MagicMock()
    
    # When get_evaluation is called internally after update_one, find_one returns the doc with _id
    stored_doc = sample_gd_result.copy()
    stored_doc["_id"] = "mongo_oid_12345"
    stored_doc["document_type"] = "gd_evaluation"
    stored_doc["created_at"] = datetime.now(timezone.utc)
    stored_doc["updated_at"] = datetime.now(timezone.utc)
    mock_collection.find_one.return_value = stored_doc

    with patch.object(gd_repo, "collection", mock_collection):
        saved = gd_repo.save_evaluation(sample_gd_result)

    assert mock_collection.update_one.called
    filter_arg, update_arg = mock_collection.update_one.call_args[0]
    kwargs = mock_collection.update_one.call_args[1]

    assert filter_arg == {"session_id": "GD-SESSION-101"}
    assert kwargs.get("upsert") is True
    assert "$set" in update_arg
    assert "$setOnInsert" in update_arg
    assert update_arg["$set"]["document_type"] == "gd_evaluation"
    assert update_arg["$set"]["topic"] == sample_gd_result["topic"]
    assert update_arg["$set"]["session_duration"] == sample_gd_result["session_duration"]
    assert update_arg["$set"]["group_transcript"] == sample_gd_result["group_transcript"]
    assert update_arg["$set"]["final_scores"] == {"P1": 7.75, "P2": 8.00}

    # Verify return value has _id popped and all fields intact
    assert saved["session_id"] == "GD-SESSION-101"
    assert "_id" not in saved
    assert saved["document_type"] == "gd_evaluation"
    assert saved["final_scores"]["P1"] == 7.75


def test_save_evaluation_validation_errors():
    """Test validation when saving invalid evaluation payloads."""
    mock_collection = MagicMock()
    with patch.object(gd_repo, "collection", mock_collection):
        # Non-dict
        with pytest.raises(ValueError, match="must be a dictionary"):
            gd_repo.save_evaluation(["not", "a", "dict"])  # type: ignore[arg-type]

        # Missing session_id
        with pytest.raises(ValueError, match="session_id is required"):
            gd_repo.save_evaluation({"topic": "AI without session_id"})

        # Empty session_id
        with pytest.raises(ValueError, match="session_id is required"):
            gd_repo.save_evaluation({"session_id": "   ", "topic": "AI"})

    assert not mock_collection.update_one.called


def test_save_evaluation_deterministic_upsert(sample_gd_result):
    """Test that saving twice uses upsert and does not create duplicates."""
    mock_collection = MagicMock()
    stored_doc = sample_gd_result.copy()
    stored_doc["_id"] = "mongo_oid_12345"
    mock_collection.find_one.return_value = stored_doc

    with patch.object(gd_repo, "collection", mock_collection):
        # First save
        gd_repo.save_evaluation(sample_gd_result)
        # Second save (update)
        sample_gd_result["topic"] = "Updated Topic Name"
        gd_repo.save_evaluation(sample_gd_result)

    assert mock_collection.update_one.call_count == 2
    # Both calls must use upsert=True with filter by session_id
    for call in mock_collection.update_one.call_args_list:
        assert call[0][0] == {"session_id": "GD-SESSION-101"}
        assert call[1].get("upsert") is True


# ==============================================================================
# GET EVALUATION TESTS
# ==============================================================================

def test_get_evaluation_found(sample_gd_result):
    """Test retrieving an existing evaluation strips _id and preserves all fields."""
    mock_collection = MagicMock()
    doc_with_id = sample_gd_result.copy()
    doc_with_id["_id"] = "mongo_obj_id_999"
    doc_with_id["document_type"] = "gd_evaluation"
    mock_collection.find_one.return_value = doc_with_id

    with patch.object(gd_repo, "collection", mock_collection):
        result = gd_repo.get_evaluation("GD-SESSION-101")

    mock_collection.find_one.assert_called_once_with({"session_id": "GD-SESSION-101"})
    assert result is not None
    assert "_id" not in result
    assert result["session_id"] == "GD-SESSION-101"
    assert result["document_type"] == "gd_evaluation"
    assert result["participants"][0]["participant_id"] == "P1"


def test_get_evaluation_not_found():
    """Test retrieving a non-existent evaluation returns None."""
    mock_collection = MagicMock()
    mock_collection.find_one.return_value = None

    with patch.object(gd_repo, "collection", mock_collection):
        result = gd_repo.get_evaluation("NON-EXISTENT")

    mock_collection.find_one.assert_called_once_with({"session_id": "NON-EXISTENT"})
    assert result is None


def test_get_evaluation_invalid_input():
    """Test get_evaluation handles empty or invalid session_id gracefully."""
    mock_collection = MagicMock()
    with patch.object(gd_repo, "collection", mock_collection):
        assert gd_repo.get_evaluation("") is None
        assert gd_repo.get_evaluation(None) is None  # type: ignore[arg-type]

    assert not mock_collection.find_one.called


# ==============================================================================
# DELETE EVALUATION TESTS
# ==============================================================================

def test_delete_evaluation_success():
    """Test successful deletion of an evaluation document."""
    mock_collection = MagicMock()
    mock_delete_result = MagicMock()
    mock_delete_result.deleted_count = 1
    mock_collection.delete_one.return_value = mock_delete_result

    with patch.object(gd_repo, "collection", mock_collection):
        deleted = gd_repo.delete_evaluation("GD-SESSION-101")

    mock_collection.delete_one.assert_called_once_with({"session_id": "GD-SESSION-101"})
    assert deleted is True


def test_delete_evaluation_not_found():
    """Test deleting a non-existent evaluation returns False."""
    mock_collection = MagicMock()
    mock_delete_result = MagicMock()
    mock_delete_result.deleted_count = 0
    mock_collection.delete_one.return_value = mock_delete_result

    with patch.object(gd_repo, "collection", mock_collection):
        deleted = gd_repo.delete_evaluation("NON-EXISTENT")

    mock_collection.delete_one.assert_called_once_with({"session_id": "NON-EXISTENT"})
    assert deleted is False


def test_delete_evaluation_invalid_input():
    """Test delete_evaluation with invalid input returns False without calling DB."""
    mock_collection = MagicMock()
    with patch.object(gd_repo, "collection", mock_collection):
        assert gd_repo.delete_evaluation("") is False
        assert gd_repo.delete_evaluation(None) is False  # type: ignore[arg-type]

    assert not mock_collection.delete_one.called


# ==============================================================================
# LIST EVALUATIONS & ERROR PROPAGATION TESTS
# ==============================================================================

def test_get_all_evaluations(sample_gd_result):
    """Test listing all evaluations with cursor handling."""
    mock_collection = MagicMock()
    mock_cursor = [
        {"_id": "id1", "session_id": "S1", "topic": "T1"},
        {"_id": "id2", "session_id": "S2", "topic": "T2"},
    ]
    mock_collection.find.return_value.sort.return_value.limit.return_value = mock_cursor

    with patch.object(gd_repo, "collection", mock_collection):
        results = gd_repo.get_all_evaluations(limit=10)

    assert len(results) == 2
    assert results[0]["session_id"] == "S1"
    assert "_id" not in results[0]
    assert results[1]["session_id"] == "S2"
    assert "_id" not in results[1]


def test_mongodb_error_propagation(sample_gd_result):
    """Test that underlying PyMongo database errors are surfaced cleanly."""
    mock_collection = MagicMock()
    mock_collection.update_one.side_effect = PyMongoError("Connection timeout")

    with patch.object(gd_repo, "collection", mock_collection):
        with pytest.raises(PyMongoError, match="Connection timeout"):
            gd_repo.save_evaluation(sample_gd_result)
